export type NivelConfianca = "alta" | "media" | "baixa";
export type Motivo = { tipo:"positivo"|"alerta"; texto:string; pontos?:number };
export type CandidatoBoleto = { id:string; cliente_id:string; carne_id:string|null; numero_parcela:number|null; total_parcelas:number|null; valor:number|string|null; data_vencimento:string|null; status:string|null; instituicao_financeira:string|null; identificador_externo:string|null; origem_boleto:string|null; clientes?:{id:string;nome_completo:string|null;cpf:string|null;telefone:string|null}|null; carnes?:{id:string;identificador_externo:string|null;instituicao_financeira:string|null;quantidade_parcelas:number|null;valor_parcela?:number|string|null;valor_total?:number|string|null}|null };
export type AnaliseCandidato=CandidatoBoleto&{pontuacao:number;percentual:number;motivos:Motivo[];pontuacao_cliente:number;pontuacao_carne:number;pontuacao_boleto:number};
export type DadosImportacao={cpf_pagador_extraido:string|null;nome_pagador_extraido:string|null;nosso_numero:string|null;identificador_externo:string|null;linha_digitavel:string|null;codigo_barras:string|null;valor_extraido:number|string|null;vencimento_extraido:string|null;numero_parcela:number|null;instituicao_financeira:string|null};
export type ClienteCandidato={id:string;nome_completo:string|null;cpf:string|null;telefone?:string|null};
export type CarneCandidato={id:string;cliente_id:string;identificador_externo:string|null;instituicao_financeira:string|null;quantidade_parcelas:number|null;valor_parcela?:number|string|null;valor_total?:number|string|null};
export function normalizarTexto(value:unknown){return String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9\s]/g," ").replace(/\s+/g," ").trim().toUpperCase();}
export function normalizarDocumento(value:unknown){return String(value??"").replace(/\D/g,"");}
function distancia(a:string,b:string){const r=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let p=r[0];r[0]=i;for(let j=1;j<=b.length;j++){const q=r[j];r[j]=a[i-1]===b[j-1]?p:Math.min(p+1,r[j-1]+1,q+1);p=q;}}return r[b.length];}
function similaridade(a:string,b:string){const x=normalizarTexto(a),y=normalizarTexto(b);if(!x||!y)return 0;if(x===y)return 1;const ax=new Set(x.split(" ").filter(Boolean)),by=new Set(y.split(" ").filter(Boolean));const inter=[...ax].filter(t=>by.has(t)).length,uniao=new Set([...ax,...by]).size;return Math.max(uniao?inter/uniao:0,1-distancia(x,y)/Math.max(x.length,y.length));}
function dinheiro(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null;}
function inst(v:unknown){return normalizarTexto(v);}
function motivo(m:Motivo[],tipo:Motivo["tipo"],texto:string,pontos?:number){m.push(pontos===undefined?{tipo,texto}:{tipo,texto,pontos});}
export function pontuarCliente(d:DadosImportacao,c:ClienteCandidato){const m:Motivo[]=[];let p=0;const cpf=normalizarDocumento(d.cpf_pagador_extraido),ccpf=normalizarDocumento(c.cpf),id=normalizarDocumento(d.identificador_externo);if(cpf&&ccpf&&cpf===ccpf){p=100;motivo(m,"positivo","CPF corresponde exatamente",100);return{pontuacao:p,motivos:m};}if(id&&id===normalizarDocumento(c.id)){p=Math.max(p,80);motivo(m,"positivo","Identificador relacionado à cliente",80);}const sim=similaridade(d.nome_pagador_extraido??"",c.nome_completo??"");if(sim>=.98){p=Math.max(p,70);motivo(m,"positivo","Nome coincide exatamente após normalização",70);}else if(sim>=.84){const pontos=Math.max(30,Math.min(60,Math.round(sim*60)));p=Math.max(p,pontos);motivo(m,"positivo","Nome semelhante após normalização",pontos);}if(cpf&&ccpf&&cpf!==ccpf)motivo(m,"alerta","CPF do PDF diverge da cliente");if(!d.cpf_pagador_extraido)motivo(m,"alerta","CPF não identificado no PDF");return{pontuacao:p,motivos:m};}
export function pontuarCarne(d:DadosImportacao,c:CarneCandidato){const m:Motivo[]=[];let p=0;const id=normalizarDocumento(d.identificador_externo),cid=normalizarDocumento(c.identificador_externo),b1=inst(d.instituicao_financeira),b2=inst(c.instituicao_financeira),v=dinheiro(d.valor_extraido),vp=dinheiro(c.valor_parcela);if(id&&cid&&id===cid){p+=100;motivo(m,"positivo","Identificador externo do carnê coincide",100);}if(b1&&b2&&b1===b2){p=Math.min(100,p+30);motivo(m,"positivo","Instituição financeira coincide",30);}if(d.numero_parcela!==null&&c.quantidade_parcelas!==null&&Number(d.numero_parcela)<=Number(c.quantidade_parcelas)){p=Math.min(100,p+20);motivo(m,"positivo","Parcela é compatível com a quantidade do carnê",20);}if(v!==null&&vp!==null&&Math.abs(v-vp)<.011){p=Math.min(100,p+20);motivo(m,"positivo","Valor da parcela coincide",20);}return{pontuacao:p,motivos:m};}
export function pontuarBoleto(d:DadosImportacao,c:CandidatoBoleto){const m:Motivo[]=[];let p=0;const nosso=normalizarDocumento(d.nosso_numero),ext=normalizarDocumento(d.identificador_externo),cid=normalizarDocumento(c.identificador_externo),v=dinheiro(d.valor_extraido),vc=dinheiro(c.valor),b1=inst(d.instituicao_financeira),b2=inst(c.instituicao_financeira);if(nosso&&cid&&nosso===cid){p+=100;motivo(m,"positivo","Nosso número coincide com identificador do boleto",100);}if(ext&&cid&&ext===cid){p=Math.max(p,100);motivo(m,"positivo","Identificador externo coincide",100);}if(v!==null&&vc!==null&&Math.abs(v-vc)<.011){p=Math.min(100,p+40);motivo(m,"positivo","Valor coincide",40);}if(d.vencimento_extraido&&c.data_vencimento&&d.vencimento_extraido===c.data_vencimento){p=Math.min(100,p+40);motivo(m,"positivo","Vencimento coincide",40);}if(d.numero_parcela!==null&&c.numero_parcela!==null&&Number(d.numero_parcela)===Number(c.numero_parcela)){p=Math.min(100,p+50);motivo(m,"positivo","Número da parcela coincide",50);}if(b1&&b2&&b1===b2){p=Math.min(100,p+20);motivo(m,"positivo","Instituição financeira coincide",20);}if(v!==null&&vc!==null&&Math.abs(v-vc)>=.011)motivo(m,"alerta","Valor diferente");if(d.vencimento_extraido&&c.data_vencimento&&d.vencimento_extraido!==c.data_vencimento)motivo(m,"alerta","Vencimento diferente");if(!d.nosso_numero)motivo(m,"alerta","Nosso número não identificado no PDF");return{pontuacao:p,motivos:m};}
export function pontuarCandidato(d:DadosImportacao,c:CandidatoBoleto):AnaliseCandidato{const cliente=pontuarCliente(d,c.clientes??{id:c.cliente_id,nome_completo:null,cpf:null}),carne=c.carnes?pontuarCarne(d,{...c.carnes,cliente_id:c.cliente_id}):{pontuacao:0,motivos:[{tipo:"alerta",texto:"Carnê não disponível para análise"} as Motivo]},boleto=pontuarBoleto(d,c);const disponiveis=[cliente.pontuacao,carne.pontuacao,boleto.pontuacao].filter((_,i)=>[cliente,carne,boleto][i].motivos.some(x=>x.tipo==="positivo"));const score=disponiveis.length?Math.round(disponiveis.reduce((a,b)=>a+b,0)/disponiveis.length):0;return{...c,pontuacao:score,percentual:score,motivos:[...cliente.motivos,...carne.motivos,...boleto.motivos],pontuacao_cliente:cliente.pontuacao,pontuacao_carne:carne.pontuacao,pontuacao_boleto:boleto.pontuacao};}
export function classificarConfianca(p:number):NivelConfianca{return p>=85?"alta":p>=60?"media":p>=30?"baixa":"baixa";}
