import { inflateSync, inflateRawSync } from "node:zlib";

export type CampoExtraido = { valor: string | number | null; origem: string | null; confianca: "alta" | "media" | "baixa" | null; motivo?: "encontrado" | "nao_encontrado_no_texto" | "texto_insuficiente" | "campo_invalido" | "campo_ambiguo" };
export type QualidadeExtracaoPdf = { caracteres: number; palavras: number; numeros: number; linhas: number; fontesToUnicode: number; suficiente: boolean; motivo: string | null };
export type DadosBoletoExtraidos = { instituicao_financeira: string | null; codigo_banco: string | null; confianca_banco?: number; metodo_identificacao_banco?: string | null; nome_beneficiario: string | null; cpf_cnpj_beneficiario: string | null; nome_pagador: string | null; cpf_pagador: string | null; nosso_numero: string | null; numero_documento: string | null; identificador_externo: string | null; linha_digitavel: string | null; codigo_barras: string | null; valor: number | null; vencimento: string | null; numero_parcela: number | null; total_parcelas: number | null; texto_extraido: string; qualidade_extracao?: QualidadeExtracaoPdf; dados_origem?: Record<string, CampoExtraido> };
type Banco = { codigo: string; nome: string; marcadores: string[] }; type CMap = Map<number, string>;
const BANCOS: Banco[] = [
  { codigo: "001", nome: "Banco do Brasil", marcadores: ["BANCO DO BRASIL", "BB.COM.BR"] },
  { codigo: "033", nome: "Santander", marcadores: ["SANTANDER", "BANCO SANTANDER"] },
  { codigo: "070", nome: "BRB", marcadores: ["BANCO DE BRASILIA", "BANCO DE BRASÍLIA", "BRB"] },
  { codigo: "364", nome: "Efí / Gerencianet", marcadores: ["BANCO EFI", "BANCO EFÍ", "GERENCIANET", "EFI BANK", "EFÍ BANK"] },
  { codigo: "748", nome: "Sicredi", marcadores: ["SICREDI", "COOPERATIVA SICREDI"] },
];
const latin = (v: Uint8Array) => Buffer.from(v).toString("latin1");
const clean = (v: string) => v.replace(/\u0000/g, "").replace(/[\u0001-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "").replace(/[\uD800-\uDFFF]/g, "");
function unzip(v: Buffer, dict: string) { if (!/\/FlateDecode/.test(dict)) return v; try { return inflateSync(v); } catch { try { return inflateRawSync(v); } catch { return v; } } }
function getObjects(pdf: Buffer) { const raw = latin(pdf), out = new Map<number, { d: string; s: Buffer | null }>(); for (const m of raw.matchAll(/(?:^|\n)(\d+)\s+0\s+obj\s*([\s\S]*?)(?:\nendobj\b)/g)) { const body = m[2], p = body.indexOf("stream"); if (p < 0) out.set(+m[1], { d: body, s: null }); else { const d = body.slice(0, p), sm = body.match(/stream\r?\n([\s\S]*?)\r?\nendstream/); out.set(+m[1], { d, s: sm ? unzip(Buffer.from(sm[1], "latin1"), d) : null }); } } return out; }
function parseCMap(s: Buffer): CMap { const t = clean(latin(s)), map: CMap = new Map(); for (const m of t.matchAll(/<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>/g)) { const a = parseInt(m[1],16), b = parseInt(m[2],16); let u = parseInt(m[3],16); for (let c=a;c<=b && c<=0xFFFF;c++) map.set(c,String.fromCodePoint(u++)); } for (const m of t.matchAll(/<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>/g)) { const b=Buffer.from(m[2],"hex"); let u=""; for(let i=0;i+1<b.length;i+=2) u+=String.fromCharCode(b.readUInt16BE(i)); map.set(parseInt(m[1],16),u); } return map; }
function unicodeMaps(objects: Map<number,{d:string;s:Buffer|null}>) { const cmaps=new Map<number,CMap>(); for(const [id,o] of objects) if(o.s && /begincmap/.test(latin(o.s))) { const m=parseCMap(o.s); if(m.size) cmaps.set(id,m); } const maps:CMap[]=[]; for(const o of objects.values()){ const r=o.d.match(/\/ToUnicode\s+(\d+)\s+0\s+R/); const m=r?cmaps.get(+r[1]):null; if(m?.size) maps.push(m); } return maps; }
function decodeType0(v: string, maps: CMap[]) { const b=Buffer.from(v,"latin1"); if(!maps.length || !b.includes(0) || b.length<2 || b.length%2) return null; const candidates=maps.map(m=>{let s="";for(let i=0;i+1<b.length;i+=2)s+=m.get(b.readUInt16BE(i))??"";return s;}).filter(Boolean); return candidates.sort((a,z)=>score(z)-score(a))[0]??null; }
function score(v:string){return [...v].filter(c=>/[\p{L}\p{N}\s.,:/()%-]/u.test(c)).length;}
function literal(v:string,maps:CMap[]){const decoded=clean(v.replace(/\\([\\()])/g,"$1").replace(/\\n/g,"\n").replace(/\\r/g,"\r").replace(/\\t/g,"\t").replace(/\\([0-7]{1,3})/g,(_,o:string)=>String.fromCharCode(parseInt(o,8)))); return decodeType0(decoded,maps)??decoded;}
function operatorText(stream:string,maps:CMap[]){const out:string[]=[]; const push=(src:string)=>{let i=0,d=0,e=false,v="";while(i<src.length){const c=src[i++];if(e){v+=`\\${c}`;e=false;continue}if(c==="\\"){e=true;continue}if(c==="("){if(d++)v+=c;continue}if(c===")"){if(--d===0){out.push(literal(v,maps));v="";continue}}if(d)v+=c;}};for(const m of stream.matchAll(/\((?:\\.|[^\\)])*\)\s*(?:Tj|TJ|'|")/g))push(m[0]);for(const m of stream.matchAll(/\[([\s\S]*?)\]\s*TJ/g))push(m[1]);for(const m of stream.matchAll(/<([0-9A-Fa-f\s]+)>\s*(?:Tj|TJ|'|")/g))out.push(decodeType0(m[1],maps)??latin(Buffer.from(m[1].replace(/\s+/g,""),"hex")));return out.filter(x=>x.trim());}
function allStreams(pdf:Buffer){const raw=latin(pdf),out:Buffer[]=[];for(const m of raw.matchAll(/stream\r?\n([\s\S]*?)\r?\nendstream/g)){const i=m.index??0;const d=raw.slice(Math.max(0,i-800),i);out.push(unzip(Buffer.from(m[1],"latin1"),d));}return out;}
function spaces(v:string){return clean(v).replace(/\u00A0/g," ").replace(/[ \t]+/g," ").replace(/\n{3,}/g,"\n\n").trim();}
function quality(t:string,fonts:number):QualidadeExtracaoPdf{const compact=t.replace(/\s+/g,"");const palavras=t.match(/[\p{L}]{2,}/gu)?.length??0;const numeros=t.match(/\d+/g)?.length??0;const linhas=t.split(/\r?\n/).filter(Boolean).length;const chars=compact.length;const numeric=chars>0&&((compact.match(/\D/g)?.length??0)/chars)<.25;const suficiente=chars>=80&&palavras>=4&&!numeric;return{caracteres:chars,palavras,numeros,linhas,fontesToUnicode:fonts,suficiente,motivo:suficiente?null:numeric?"texto dominado por sequências numéricas":"texto extraído insuficiente"};}
export function extrairTextoPdf(pdf:Buffer){if(pdf.length<5||pdf.subarray(0,5).toString("ascii")!=="%PDF-")throw new Error("O arquivo enviado não é um PDF válido.");const objects=getObjects(pdf),maps=unicodeMaps(objects);let text=spaces(allStreams(pdf).flatMap(s=>operatorText(latin(s),maps)).join("\n"));let q=quality(text,maps.length);if(!q.suficiente){text=spaces([text,clean(latin(pdf)).replace(/[^\x20-\x7E\xC0-\xFF\n\r\t]/g," ")].join("\n"));q=quality(text,maps.length);}if(!q.suficiente)throw new Error(`PDF SEM TEXTO EXTRAÍVEL: ${q.motivo??"qualidade insuficiente"}`);return text;}
export function normalizarTexto(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();} export function somenteDigitos(v:string|null|undefined){return String(v??"").replace(/\D/g,"");}
function lines(t:string){return t.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);} function fragmented(v:string){return v.replace(/(?<=\d)[ .-]+(?=\d)/g,"");}
const LABELS=new Set(["PAGADOR","BENEFICIARIO","BENEFICIÁRIO","VENCIMENTO","VALOR DO DOCUMENTO","VALOR COBRADO","NOSSO NUMERO","NOSSO NÚMERO","Nº DO DOCUMENTO","NUMERO DO DOCUMENTO","NÚMERO DO DOCUMENTO","CNPJ/CPF","PARCELA/ PLANO","PARCELA/PLANO","DATA DE PROCESSAMENTO","DATA DO DOCUMENTO","FICHA DE COMPENSAÇÃO"]);
function context(t:string,labels:string[],validate:(v:string)=>string|number|null){const ls=lines(t),want=labels.map(normalizarTexto);for(let i=0;i<ls.length;i++){if(!want.some(x=>normalizarTexto(ls[i]).includes(x)))continue;for(let j=i;j<Math.min(i+30,ls.length);j++){let candidate=ls[j];if(j===i){candidate=candidate.replace(new RegExp(`.*?(?:${labels.join("|")})\\s*[:\\-]?\\s*`,"i"),"");}if(LABELS.has(normalizarTexto(candidate)))continue;const v=validate(candidate);if(v!==null&&String(candidate).trim()!=="")return{valor:v,origem:j===i?ls[i]:`${ls[i]} → ${ls[j]}`};}}return null;}
function money(v:string){const m=v.match(/R\$\s*(\d{1,3}(?:\.\d{3})*(?:,\d{1,2})?|\d+(?:[.,]\d{1,2})?)/i)??v.match(/\b\d{1,3}(?:\.\d{3})*,\d{2}\b/);if(!m)return null;const r=m[1]??m[0],n=Number(r.includes(",")?r.replace(/\./g,"").replace(",","."):r.replace(/,/g,""));return Number.isFinite(n)?n:null;}
function date(v:string){const m=v.match(/\b(\d{2})[\/.-](\d{2})[\/.-](\d{4})\b/);return m?`${m[3]}-${m[2]}-${m[1]}`:null;} function digits(v:string,min:number,max:number){const d=somenteDigitos(fragmented(v));return d.length>=min&&d.length<=max?d:null;} function textValue(v:string){const x=v.trim().replace(/^[|:;\-]+\s*/,"");return x&&!LABELS.has(normalizarTexto(x))&&!/^(não|nao|n\/a|-)$/i.test(x)?x:null;}
function findLine(t:string){return [...t.matchAll(/(?:\d[\s.-]?){47,48}/g)].map(m=>somenteDigitos(m[0])).find(x=>x.length===47||x.length===48)??null;} function findBar(t:string,l:string|null){const c=[...t.matchAll(/\b\d{44}\b/g)].map(m=>m[0]);if(l?.length===47){const r=`${l.slice(0,4)}${l.slice(32,33)}${l.slice(33)}${l.slice(4,9)}${l.slice(10,20)}${l.slice(21,31)}`;if(r.length===44)c.unshift(r);}return c[0]??null;}
export function identificarInstituicao(text:string,line:string|null){const n=normalizarTexto(text),ev:Array<{b:Banco;p:number;m:string}>=[];for(const b of BANCOS){if(line?.slice(0,3)===b.codigo)ev.push({b,p:80,m:"codigo_bancario_linha_digitavel"});if(b.marcadores.some(x=>n.includes(normalizarTexto(x))))ev.push({b,p:55,m:"texto_identificador_instituicao"});}if(!ev.length)return{nome:null,codigo:null,confianca:0,origem:null};const g=new Map<string,{b:Banco;p:number;m:string[]}>();for(const e of ev){const x=g.get(e.b.codigo)??{b:e.b,p:0,m:[]};x.p+=e.p;x.m.push(e.m);g.set(e.b.codigo,x);}const a=[...g.values()].sort((x,y)=>y.p-x.p),best=a[0],second=a[1];if(second&&second.p>=best.p-10)return{nome:null,codigo:null,confianca:0,origem:"evidências conflitantes"};return{nome:best.b.nome,codigo:best.b.codigo,confianca:Math.min(99,best.p),origem:[...new Set(best.m)].join("+")};}
const field=(r:{valor:string|number|null;origem:string}|null,missing:CampoExtraido["motivo"]):CampoExtraido=>r?{valor:r.valor,origem:r.origem,confianca:"alta",motivo:"encontrado"}:{valor:null,origem:null,confianca:null,motivo:missing};
export function extrairDadosBoleto(pdf:Buffer):DadosBoletoExtraidos{const text=extrairTextoPdf(pdf),l=findLine(text),b=identificarInstituicao(text,l),get=(x:string[],v:(z:string)=>string|number|null)=>context(text,x,v);const pag=get(["Pagador","Nome do pagador"],textValue);const pagCpf=pag?.valor&&typeof pag.valor==="string"?pag.valor.match(/(?:-|–)\s*(\d{11,14})\s*$/)?.[1]??null:null;const cpf=get(["CPF do pagador","CPF"],v=>digits(v,11,14))??(pagCpf?{valor:pagCpf,origem:"CPF presente na identificação do pagador"}:null);const nosso=get(["Nosso Número","Nosso Numero"],v=>digits(v,3,30));const doc=get(["Número do Documento","Numero do Documento","Nº do Documento"],v=>digits(v,1,30));const ext=get(["Identificador externo","Referência adicional","Referencia adicional"],textValue);const valor=get(["Valor do Documento","Valor Cobrado","Valor a pagar"],money);const venc=get(["Vencimento","Data de Vencimento"],date);const ben=get(["Beneficiário","Beneficiario"],textValue);const cpfBen=get(["CNPJ/CPF","CPF/CNPJ","CNPJ"],v=>digits(v,11,14));const parc=text.match(/\b(\d{1,3})\s*\/\s*(\d{1,3})\b/);const bar=findBar(text,l);const q=quality(text,0),missing=q.suficiente?"nao_encontrado_no_texto":"texto_insuficiente";const origem:Record<string,CampoExtraido>={nome_pagador:field(pag,missing),cpf_pagador:field(cpf,missing),nosso_numero:field(nosso,missing),numero_documento:field(doc,missing),identificador_externo:field(ext,missing),valor:field(valor,missing),vencimento:field(venc,missing),nome_beneficiario:field(ben,missing),cpf_cnpj_beneficiario:field(cpfBen,missing),instituicao_financeira:{valor:b.nome,origem:b.origem,confianca:b.nome?(b.confianca>=80?"alta":"media"):null,motivo:b.nome?"encontrado":"nao_encontrado_no_texto"},linha_digitavel:{valor:l,origem:l?"sequência numérica compatível":null,confianca:l?"media":null,motivo:l?"encontrado":"nao_encontrado_no_texto"},codigo_barras:{valor:bar,origem:bar?"código de barras de 44 dígitos":null,confianca:bar?"media":null,motivo:bar?"encontrado":"nao_encontrado_no_texto"}};return{instituicao_financeira:b.nome,codigo_banco:b.codigo,confianca_banco:b.confianca,metodo_identificacao_banco:b.origem,nome_beneficiario:typeof ben?.valor==="string"?ben.valor:null,cpf_cnpj_beneficiario:typeof cpfBen?.valor==="string"?cpfBen.valor:null,nome_pagador:typeof pag?.valor==="string"?pag.valor:null,cpf_pagador:typeof cpf?.valor==="string"?cpf.valor:null,nosso_numero:typeof nosso?.valor==="string"?nosso.valor:null,numero_documento:typeof doc?.valor==="string"?doc.valor:null,identificador_externo:typeof ext?.valor==="string"?ext.valor:null,linha_digitavel:l,codigo_barras:bar,valor:typeof valor?.valor==="number"?valor.valor:null,vencimento:typeof venc?.valor==="string"?venc.valor:null,numero_parcela:parc?Number(parc[1]):null,total_parcelas:parc?Number(parc[2]):null,texto_extraido:text,qualidade_extracao:q,dados_origem:origem};}
export function normalizarNome(v:string|null|undefined){return normalizarTexto(String(v??"")).replace(/[^A-Z0-9 ]/g," ").replace(/\s+/g," ").trim();} export function normalizarCpf(v:string|null|undefined){return somenteDigitos(v);}
