import { inflateSync, inflateRawSync } from "node:zlib";

export type CampoExtraido = { valor: string | number | null; origem: string | null; confianca: "alta" | "media" | "baixa" | null };
export type DadosBoletoExtraidos = {
  instituicao_financeira: string | null; codigo_banco: string | null; nome_beneficiario: string | null; cpf_cnpj_beneficiario: string | null;
  nome_pagador: string | null; cpf_pagador: string | null; nosso_numero: string | null; numero_documento: string | null;
  identificador_externo: string | null; linha_digitavel: string | null; codigo_barras: string | null; valor: number | null;
  vencimento: string | null; numero_parcela: number | null; total_parcelas: number | null; texto_extraido: string;
  dados_origem?: Record<string, CampoExtraido>;
};

type Banco = { codigo: string; nome: string; marcadores: string[] };
const BANCOS: Banco[] = [
  { codigo: "001", nome: "Banco do Brasil", marcadores: ["BANCO DO BRASIL", "BB.COM.BR"] },
  { codigo: "033", nome: "Santander", marcadores: ["SANTANDER", "BANCO SANTANDER"] },
  { codigo: "070", nome: "BRB", marcadores: ["BANCO DE BRASILIA", "BANCO DE BRASÍLIA", "BRB"] },
  { codigo: "364", nome: "Efí / Gerencianet", marcadores: ["BANCO EFI", "BANCO EFÍ", "GERENCIANET", "EFI BANK", "EFÍ BANK"] },
  { codigo: "748", nome: "Sicredi", marcadores: ["SICREDI", "COOPERATIVA SICREDI"] },
];
function latin1(bytes: Uint8Array) { return Buffer.from(bytes).toString("latin1"); }
function sanitizarTexto(value: string) { return value.replace(/\u0000/g, "").replace(/[\u0001-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "").replace(/\uFFFE|\uFFFF/g, "").replace(/[\uD800-\uDFFF]/g, ""); }
function decodificarLiteral(value: string) { return sanitizarTexto(value.replace(/\\([\\()])/g, "$1").replace(/\\n/g, "\n").replace(/\\r/g, "\r").replace(/\\t/g, "\t").replace(/\\b/g, "\b").replace(/\\f/g, "\f").replace(/\\([0-7]{1,3})/g, (_, o: string) => String.fromCharCode(parseInt(o, 8)))); }
function decodificarHex(value: string) { const clean = value.replace(/\s+/g, ""); const even = clean.length % 2 ? `${clean}0` : clean; return sanitizarTexto(Buffer.from(even, "hex").toString("latin1")); }
function extrairStringsDeOperadores(stream: string) {
  const out: string[] = [];
  const pushLiteralStrings = (source: string) => { let i = 0; while (i < source.length) { if (source[i] !== "(") { i++; continue; } i++; let depth = 1; let escaped = false; let value = ""; while (i < source.length && depth > 0) { const ch = source[i++]; if (escaped) { value += `\\${ch}`; escaped = false; continue; } if (ch === "\\") { escaped = true; continue; } if (ch === "(") { depth++; value += ch; continue; } if (ch === ")") { depth--; if (depth === 0) break; } value += ch; } out.push(decodificarLiteral(value)); } };
  for (const match of stream.matchAll(/\((?:\\.|[^\\)])*\)\s*(?:Tj|TJ|'|\")/gs)) pushLiteralStrings(match[0]);
  for (const match of stream.matchAll(/\[(.*?)\]\s*TJ/gs)) pushLiteralStrings(match[1]);
  for (const match of stream.matchAll(/<([0-9A-Fa-f\s]+)>\s*(?:Tj|TJ|'|\")/gs)) out.push(decodificarHex(match[1]));
  return out.map(sanitizarTexto).filter((v) => v.trim());
}
function extrairStreams(pdf: Buffer) { const raw = latin1(pdf); const streams: Buffer[] = []; for (const match of raw.matchAll(/stream\r?\n([\s\S]*?)\r?\nendstream/g)) { const start = match.index ?? 0; const dictionary = raw.slice(Math.max(0, start - 500), start); const source = Buffer.from(match[1], "latin1"); if (/\/FlateDecode/.test(dictionary)) { try { streams.push(inflateSync(source)); continue; } catch { try { streams.push(inflateRawSync(source)); continue; } catch { /* segue */ } } } streams.push(source); } return streams; }
export function extrairTextoPdf(pdf: Buffer) { if (pdf.length < 5 || pdf.subarray(0, 5).toString("ascii") !== "%PDF-") throw new Error("O arquivo enviado não é um PDF válido."); const textos = extrairStreams(pdf).flatMap((c) => extrairStringsDeOperadores(latin1(c))); const fallback = sanitizarTexto(latin1(pdf)).replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g, " "); const text = sanitizarTexto([...textos, fallback.match(/[\x20-\x7E\xC0-\xFF\n\r\t]{4,}/g)?.join(" ") ?? ""].join("\n").replace(/[ \t]+/g, " ").replace(/\n{3,}/g, "\n\n").trim()); if (text.replace(/[^\p{L}\p{N}]/gu, "").length < 20) throw new Error("PDF SEM TEXTO EXTRAÍVEL"); return text; }
export function normalizarTexto(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase(); }
export function somenteDigitos(value: string | null | undefined) { return String(value ?? "").replace(/\D/g, ""); }
function linhas(text: string) { return text.split(/\r?\n/).map((l) => l.trim()).filter(Boolean); }
function procurarComContexto(text: string, labels: string[], validator: (v: string) => string | number | null) { const ls = linhas(text); const re = new RegExp(`(?:${labels.join("|")})\\s*[:\\-]?\\s*(.*)$`, "i"); for (let i = 0; i < ls.length; i++) { const same = ls[i].match(re); if (!same) continue; const direct = validator(same[1]); if (direct !== null) return { valor: direct, origem: ls[i] }; for (let j = i + 1; j <= Math.min(i + 3, ls.length - 1); j++) { const next = validator(ls[j]); if (next !== null) return { valor: next, origem: `${ls[i]} → ${ls[j]}` }; } } return null; }
function valorBrasileiro(v: string) { const m = v.replace(/R\$\s*/i, "").match(/\d{1,3}(?:\.\d{3})*(?:,\d{1,2})?|\d+(?:\.\d{1,2})?/); if (!m) return null; const n = Number(m[0].includes(",") ? m[0].replace(/\./g, "").replace(",", ".") : m[0]); return Number.isFinite(n) ? n : null; }
function dataIso(v: string) { const br = v.match(/\b(\d{2})[\\/.-](\d{2})[\\/.-](\d{4})\b/); if (br) return `${br[3]}-${br[2]}-${br[1]}`; const iso = v.match(/\b(\d{4})[\\/.-](\d{2})[\\/.-](\d{2})\b/); return iso ? `${iso[1]}-${iso[2]}-${iso[3]}` : null; }
function digits(v: string, min: number, max: number) { const d = somenteDigitos(v); return d.length >= min && d.length <= max ? d : null; }
function textoValor(v: string) { const x = v.trim(); return x && !/^(não|nao|n\/a)$/i.test(x) ? x : null; }
function encontrarLinhaDigitavel(text: string) { const candidates = [...text.matchAll(/(?:\d[ .-]?){47,48}/g)].map((m) => somenteDigitos(m[0])); return candidates.find((d) => d.length === 47 || d.length === 48) ?? null; }
function encontrarCodigoBarras(text: string, linha: string | null) { const candidates = [...text.matchAll(/\b\d{44}\b/g)].map((m) => m[0]); if (linha?.length === 47) { const rebuilt = `${linha.slice(0, 4)}${linha.slice(32, 33)}${linha.slice(33)}${linha.slice(4, 9)}${linha.slice(10, 20)}${linha.slice(21, 31)}`; if (rebuilt.length === 44) candidates.unshift(rebuilt); } return candidates[0] ?? null; }
export function identificarInstituicao(text: string, linhaDigitavel: string | null) { const normalized = normalizarTexto(text); const code = linhaDigitavel?.slice(0, 3) ?? ""; const byCode = BANCOS.find((b) => b.codigo === code); if (byCode) return { nome: byCode.nome, codigo: byCode.codigo, origem: "código bancário da linha digitável" }; const byMarker = BANCOS.find((b) => b.marcadores.some((m) => normalized.includes(normalizarTexto(m)))); return byMarker ? { nome: byMarker.nome, codigo: byMarker.codigo, origem: "texto identificador da instituição" } : { nome: null, codigo: null, origem: null }; }
export function extrairDadosBoleto(pdf: Buffer): DadosBoletoExtraidos {
  const texto = extrairTextoPdf(pdf); const linha = encontrarLinhaDigitavel(texto); const banco = identificarInstituicao(texto, linha); const get = (labels: string[], validator: (v: string) => string | number | null) => procurarComContexto(texto, labels, validator);
  const nome = get(["Nome do pagador", "Pagador", "Cliente"], textoValor); const cpf = get(["CPF do pagador", "CPF/CNPJ", "CPF"], (v) => digits(v, 11, 14)); const nosso = get(["Nosso Número", "Nosso Numero"], (v) => digits(v, 3, 30)); const documento = get(["Número do Documento", "Numero do Documento", "Nº do Documento", "Documento"], (v) => digits(v, 1, 30)); const identificador = get(["Identificador externo", "Referência adicional", "Referencia adicional", "Referência"], textoValor); const valor = get(["Valor do Documento", "Valor a pagar", "Valor Cobrado", "Valor"], valorBrasileiro); const vencimento = get(["Data de Vencimento", "Vencimento", "Vencimento do Documento"], dataIso); const beneficiario = get(["Nome do beneficiário", "Nome do beneficiario", "Beneficiário", "Beneficiario"], textoValor); const cpfBeneficiario = get(["CPF/CNPJ do beneficiário", "CNPJ do beneficiário", "CNPJ"], (v) => digits(v, 11, 14));
  const parcela = texto.match(/\bparcela\s*(\d{1,3})\s*(?:de|\/)\s*(\d{1,3})\b/i); const codigoBarras = encontrarCodigoBarras(texto, linha); const origem: Record<string, CampoExtraido> = {}; const registrar = (k: string, r: { valor: string | number | null; origem: string } | null) => { origem[k] = { valor: r?.valor ?? null, origem: r?.origem ?? null, confianca: r ? "alta" : null }; };
  registrar("nome_pagador", nome); registrar("cpf_pagador", cpf); registrar("nosso_numero", nosso); registrar("numero_documento", documento); registrar("identificador_externo", identificador); registrar("valor", valor); registrar("vencimento", vencimento); registrar("nome_beneficiario", beneficiario); registrar("cpf_cnpj_beneficiario", cpfBeneficiario); origem.instituicao_financeira = { valor: banco.nome, origem: banco.origem, confianca: banco.nome ? "alta" : null }; origem.linha_digitavel = { valor: linha, origem: linha ? "sequência numérica compatível" : null, confianca: linha ? "media" : null }; origem.codigo_barras = { valor: codigoBarras, origem: codigoBarras ? "código de barras de 44 dígitos" : null, confianca: codigoBarras ? "media" : null };
  return { instituicao_financeira: banco.nome, codigo_banco: banco.codigo, nome_beneficiario: beneficiario?.valor as string | null ?? null, cpf_cnpj_beneficiario: cpfBeneficiario?.valor as string | null ?? null, nome_pagador: nome?.valor as string | null ?? null, cpf_pagador: cpf?.valor as string | null ?? null, nosso_numero: nosso?.valor as string | null ?? null, numero_documento: documento?.valor as string | null ?? null, identificador_externo: identificador?.valor as string | null ?? null, linha_digitavel: linha, codigo_barras: codigoBarras, valor: typeof valor?.valor === "number" ? valor.valor : null, vencimento: vencimento?.valor as string | null ?? null, numero_parcela: parcela ? Number(parcela[1]) : null, total_parcelas: parcela ? Number(parcela[2]) : null, texto_extraido: texto, dados_origem: origem };
}
export function normalizarNome(value: string | null | undefined) { return normalizarTexto(String(value ?? "")).replace(/[^A-Z0-9 ]/g, " ").replace(/\s+/g, " ").trim(); }
export function normalizarCpf(value: string | null | undefined) { return somenteDigitos(value); }
