"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, CircleAlert, Landmark } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, Panel, SectionHeading, StatusPill } from "@/components/admin/ExecutiveUI";
import { Button } from "@/components/ui/Button";
import { formatarCpf } from "@/lib/cpf";
import { formatarMoeda } from "@/lib/utils";

function dataBR(v: string | null) { if (!v) return "—"; const [a,m,d] = v.split("-").map(Number); return new Date(a,m-1,d).toLocaleDateString("pt-BR"); }

export default function CarneDetalhePage({ params }: { params: { id: string } }) {
  const [carne, setCarne] = useState<any>(null); const [resumo, setResumo] = useState<any>(null); const [carregando, setCarregando] = useState(true); const [salvando, setSalvando] = useState(false);
  async function carregar() { setCarregando(true); try { const r = await fetch(`/api/admin/carnes/${params.id}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.erro); setCarne(d.carne); setResumo(d.resumo); } catch (e) { toast.error(e instanceof Error ? e.message : "Não foi possível carregar o carnê."); } finally { setCarregando(false); } }
  useEffect(() => { void carregar(); }, [params.id]);
  async function alternarStatus() { if (!carne) return; setSalvando(true); try { const status = carne.status === "concluido" ? "ativo" : "concluido"; const r = await fetch(`/api/admin/carnes/${params.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const d = await r.json(); if (!r.ok) throw new Error(d.erro); setCarne((x: any) => ({ ...x, status: d.carne.status })); toast.success(status === "concluido" ? "Carnê marcado como concluído." : "Carnê reativado."); } catch (e) { toast.error(e instanceof Error ? e.message : "Não foi possível atualizar o status."); } finally { setSalvando(false); } }
  if (carregando) return <div className="space-y-5"><div className="h-7 w-48 animate-pulse rounded bg-blush/60" /><Panel><div className="h-40 animate-pulse rounded-xl bg-blush/40" /></Panel></div>;
  if (!carne) return <Panel><p className="text-sm text-burgundy">Carnê não encontrado.</p></Panel>;
  const cliente = carne.clientes;
  return <div className="space-y-5 pb-10">
    <Link href="/admin/carnes" className="inline-flex items-center gap-2 text-xs font-semibold text-burgundy/60 hover:text-burgundy"><ArrowLeft className="h-3.5 w-3.5" /> Voltar para carnês</Link>
    <div className="flex flex-wrap items-start justify-between gap-4"><PageHeader eyebrow="Financeiro / Carnês" title={carne.identificador_externo} description="Detalhamento do carnê externo e das parcelas já registradas no sistema." /><Button size="sm" variant="secondary" onClick={alternarStatus} disabled={salvando}>{carne.status === "concluido" ? "Reativar carnê" : "Marcar como concluído"}</Button></div>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><Resumo label="Valor total" value={formatarMoeda(resumo.valor_total)} /><Resumo label="Total pago" value={formatarMoeda(resumo.total_pago)} tone="success" /><Resumo label="Total pendente" value={formatarMoeda(resumo.total_pendente)} tone="gold" /><Resumo label="Parcelas" value={String(resumo.quantidade_parcelas)} /><Resumo label="Pagas" value={String(resumo.parcelas_pagas)} tone="success" /><Resumo label="Pendentes" value={String(resumo.parcelas_pendentes)} tone="gold" /></div>
    <div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><Panel><SectionHeading title="Cliente" /><div className="mt-4 space-y-3"><Info label="Nome" value={cliente?.nome_completo} /><Info label="CPF" value={cliente?.cpf ? formatarCpf(cliente.cpf) : "—"} /><Info label="Telefone" value={cliente?.telefone} /><Info label="E-mail" value={cliente?.email} /></div></Panel><Panel><SectionHeading title="Informações do carnê" /><div className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Instituição" value={carne.instituicao_financeira} /><Info label="Identificador externo" value={carne.identificador_externo} /><Info label="Data de geração" value={dataBR(carne.data_geracao)} /><Info label="Quantidade" value={`${carne.quantidade_parcelas} parcelas`} /><Info label="Valor da parcela" value={formatarMoeda(carne.valor_parcela)} /><Info label="Status" value={carne.status === "concluido" ? "Concluído" : "Ativo"} /></div></Panel></div>
    <Panel className="overflow-hidden p-0"><div className="border-b border-rose/10 p-4 sm:p-5"><SectionHeading title="Parcelas / boletos" description="Os registros abaixo são os boletos existentes vinculados ao carnê. Nenhum código bancário é gerado aqui." /></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left"><thead className="bg-blush/20"><tr>{["Parcela","Vencimento","Valor","Identificador externo","Origem","Status","Pagamento"].map(h => <th key={h} className="px-4 py-3 text-[9px] font-bold uppercase tracking-wider text-clay/40">{h}</th>)}</tr></thead><tbody className="divide-y divide-rose/8">{carne.boletos.map((b: any) => <tr key={b.id}><td className="px-4 py-3 text-xs font-semibold text-burgundy">{String(b.numero_parcela).padStart(2,"0")}/{b.total_parcelas}</td><td className="px-4 py-3 text-xs text-clay/60">{dataBR(b.data_vencimento)}</td><td className="px-4 py-3 text-xs font-bold text-burgundy">{formatarMoeda(Number(b.valor))}</td><td className="px-4 py-3 text-xs text-clay/60">{b.identificador_externo ?? "—"}</td><td className="px-4 py-3 text-[10px] uppercase tracking-wider text-clay/50">{b.origem_boleto === "externo" ? "Externo" : "Sistema"}</td><td className="px-4 py-3"><StatusPill tone={b.status === "pago" ? "success" : "gold"}>{b.status === "pago" ? "Pago" : b.status === "nao_pago" ? "Não pago" : b.status}</StatusPill></td><td className="px-4 py-3 text-xs text-clay/55">{dataBR(b.data_pagamento)}</td></tr>)}</tbody></table></div>{carne.boletos.length === 0 && <div className="p-10 text-center text-xs text-clay/45">Nenhuma parcela real vinculada a este carnê.</div>}</Panel>
    <Panel><div className="flex items-start gap-3"><div className="rounded-xl bg-blush/60 p-2 text-burgundy"><Landmark className="h-4 w-4" /></div><div><p className="text-sm font-semibold text-burgundy">Conciliação Bancária</p><p className="mt-1 text-[11px] leading-5 text-clay/45">O vínculo estrutural já é preparado pelo boleto: cliente + boleto + carnê. A baixa financeira automática continua desativada nesta etapa.</p></div></div></Panel>
  </div>;
}
function Resumo({label,value,tone="neutral"}:{label:string;value:string;tone?:string}) { return <div className="rounded-xl border border-rose/10 bg-white/65 p-4 dark:border-white/8 dark:bg-white/[0.035]"><p className="text-[9px] font-bold uppercase tracking-wider text-clay/40">{label}</p><p className={`mt-1.5 text-lg font-semibold ${tone === "success" ? "text-success" : tone === "gold" ? "text-gold" : "text-burgundy"}`}>{value}</p></div>; }
function Info({label,value}:{label:string;value?:string|null}) { return <div><p className="text-[9px] font-bold uppercase tracking-wider text-clay/40">{label}</p><p className="mt-1 text-sm font-medium text-burgundy dark:text-[#eadbd8]">{value || "—"}</p></div>; }
