"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, CircleAlert, FileText, Search, ShieldCheck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, Panel, SectionHeading, StatusPill } from "@/components/admin/ExecutiveUI";
import { Button } from "@/components/ui/Button";
import { Input, Select } from "@/components/ui/Input";
import { formatarCpf } from "@/lib/cpf";
import { formatarMoeda } from "@/lib/utils";

const statusLabel:any={pendente:"Aguardando análise",analisado:"Analisado",aguardando_confirmacao:"Aguardando confirmação",vinculado:"Vinculado",ignorado:"Ignorado"};
function dataBR(v:any){if(!v)return "Não identificado";const[a,m,d]=String(v).split("-").map(Number);return Number.isFinite(a)?new Date(a,m-1,d).toLocaleDateString("pt-BR"):"Não identificado";}
function campo(label:string,v:any){return <div><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-clay/40">{label}</p><p className="mt-1 break-words text-xs font-medium text-burgundy dark:text-[#eadbd8]">{v===null||v===undefined||v===""?"Não identificado":String(v)}</p></div>}

export default function VinculacaoDetalhe({params}:{params:{id:string}}){
 const[item,setItem]=useState<any>(null);const[candidatos,setCandidatos]=useState<any[]>([]);const[clientes,setClientes]=useState<any[]>([]);const[carnes,setCarnes]=useState<any[]>([]);const[boletos,setBoletos]=useState<any[]>([]);const[clienteId,setClienteId]=useState("");const[carneId,setCarneId]=useState("");const[boletoId,setBoletoId]=useState("");const[analisando,setAnalisando]=useState(false);const[salvando,setSalvando]=useState(false);const[busca,setBusca]=useState("");
 async function carregar(){const r=await fetch(`/api/admin/vinculacao-boletos/${params.id}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.erro);setItem(d.importacao);setCandidatos(d.candidatos??[]);setClienteId(d.importacao.cliente_vinculado_id??d.importacao.cliente_sugerido_id??"");setCarneId(d.importacao.carne_vinculado_id??d.importacao.carne_sugerido_id??"");setBoletoId(d.importacao.boleto_vinculado_id??d.importacao.boleto_sugerido_id??"");}
 useEffect(()=>{void carregar().catch(e=>toast.error(e instanceof Error?e.message:"Falha ao carregar."));void fetch("/api/admin/clientes",{cache:"no-store"}).then(r=>r.json()).then(d=>setClientes(d.clientes??[])).catch(()=>undefined)},[params.id]);
 useEffect(()=>{if(!clienteId){setCarnes([]);setBoletos([]);return;}Promise.all([fetch(`/api/admin/carnes?cliente_id=${encodeURIComponent(clienteId)}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/admin/boletos?cliente_id=${encodeURIComponent(clienteId)}`,{cache:"no-store"}).then(r=>r.json())]).then(([c,b])=>{setCarnes(c.carnes??[]);setBoletos(b.boletos??[]);}).catch(()=>toast.error("Falha ao carregar cliente/carnês/boletos."))},[clienteId]);
 async function analisar(){setAnalisando(true);try{const r=await fetch(`/api/admin/vinculacao-boletos/${params.id}/analisar`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.erro);setItem(d.importacao);setCandidatos(d.analise?.candidatos??[]);setClienteId(d.analise?.principal?.cliente_id??"");setCarneId(d.analise?.principal?.carne_id??"");setBoletoId(d.analise?.principal?.id??"");toast.success("Análise concluída.");}catch(e){toast.error(e instanceof Error?e.message:"Falha na análise.")}finally{setAnalisando(false)}}
 async function confirmar(manual=false){if(!clienteId||!carneId||!boletoId){toast.error("Selecione cliente, carnê e boleto existente.");return}setSalvando(true);try{const rota=manual?"manual":"confirmar";const r=await fetch(`/api/admin/vinculacao-boletos/${params.id}/${rota}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cliente_id:clienteId,carne_id:carneId,boleto_id:boletoId})});const d=await r.json();if(!r.ok)throw new Error(d.erro);setItem(d.importacao);toast.success("Vinculação confirmada sem alterar baixa, valor ou vencimento.");}catch(e){toast.error(e instanceof Error?e.message:"Falha ao confirmar.")}finally{setSalvando(false)}}
 if(!item)return <Panel><p className="text-sm text-burgundy">Carregando análise…</p></Panel>;
 const nivel=item.nivel_confianca;const percentual=item.pontuacao_confianca===null?0:Math.min(100,Number(item.pontuacao_confianca));const principal=candidatos[0];const motivos=principal?.motivos??[];const selecionado=boletos.find(b=>b.id===boletoId)||item.boletos;const carneSelecionado=carnes.find(c=>c.id===carneId)||item.carnes;const clienteSelecionada=clientes.find(c=>c.id===clienteId)||item.clientes;
 return <div className="space-y-5 pb-10"><Link href="/admin/vinculacao-boletos" className="inline-flex items-center gap-2 text-xs font-semibold text-burgundy/60 hover:text-burgundy"><ArrowLeft className="h-3.5 w-3.5"/>Voltar para a central</Link><PageHeader eyebrow="Financeiro / Inteligência" title="Análise de vinculação" description={item.arquivo_nome??"Importação de boleto"}/>
 <div className="grid gap-5 xl:grid-cols-[1.08fr_0.92fr]">
  <div className="space-y-5"><Panel><SectionHeading title="Dados extraídos do PDF" description="O sistema não preenche campos que não foram encontrados no documento."/><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{campo("Banco",item.instituicao_financeira)}{campo("Nome",item.nome_pagador_extraido)}{campo("CPF",item.cpf_pagador_extraido?formatarCpf(item.cpf_pagador_extraido):null)}{campo("Nosso Número",item.nosso_numero)}{campo("Identificador",item.identificador_externo)}{campo("Linha digitável",item.linha_digitavel)}{campo("Código de barras",item.codigo_barras)}{campo("Valor",item.valor_extraido===null?null:formatarMoeda(Number(item.valor_extraido)))}{campo("Vencimento",dataBR(item.vencimento_extraido))}{campo("Parcela",item.numero_parcela)}{campo("Documento",item.numero_documento)}{campo("Arquivo",item.arquivo_nome)}</div></Panel>
  <Panel><SectionHeading title="Vinculação manual" description="Cliente → carnê → boleto existente. O backend valida toda a cadeia antes de confirmar."/><div className="mt-5 grid gap-4 lg:grid-cols-3"><label className="space-y-1.5"><span className="text-[9px] font-bold uppercase tracking-[0.14em] text-clay/40">Cliente</span><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-clay/30"/><Input className="pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Filtrar clientes…"/></div><Select value={clienteId} onChange={e=>{setClienteId(e.target.value);setCarneId("");setBoletoId("")}}><option value="">Selecione uma cliente</option>{clientes.filter(c=>!busca||`${c.nome_completo} ${c.cpf}`.toLowerCase().includes(busca.toLowerCase())).map(c=><option key={c.id} value={c.id}>{c.nome_completo} · {formatarCpf(c.cpf)}</option>)}</Select></label><label className="space-y-1.5"><span className="text-[9px] font-bold uppercase tracking-[0.14em] text-clay/40">Carnê</span><Select disabled={!clienteId} value={carneId} onChange={e=>{setCarneId(e.target.value);setBoletoId("")}}><option value="">Selecione um carnê</option>{carnes.map(c=><option key={c.id} value={c.id}>{c.identificador_externo} · {c.instituicao_financeira}</option>)}</Select></label><label className="space-y-1.5"><span className="text-[9px] font-bold uppercase tracking-[0.14em] text-clay/40">Boleto</span><Select disabled={!carneId} value={boletoId} onChange={e=>setBoletoId(e.target.value)}><option value="">Selecione um boleto</option>{boletos.filter(b=>b.carne_id===carneId).map(b=><option key={b.id} value={b.id}>{String(b.numero_parcela).padStart(2,"0")}/{b.total_parcelas} · {formatarMoeda(Number(b.valor))} · {dataBR(b.data_vencimento)}</option>)}</Select></label></div><div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="secondary" disabled={salvando} onClick={()=>void confirmar(true)}>Selecionar manualmente</Button><Button disabled={salvando} onClick={()=>void confirmar(false)}><Check className="h-3.5 w-3.5"/>Confirmar vinculação</Button></div></Panel></div>
  <div className="space-y-5"><Panel className="border-burgundy/10"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-burgundy/45">Análise inteligente</p><p className="mt-2 text-3xl font-semibold text-burgundy">{nivel?`${String(nivel).toUpperCase()} · ${percentual}%`:"PENDENTE"}</p><p className="mt-1 text-[11px] text-clay/45">Pontuação por regras determinísticas, sem IA externa.</p></div><ShieldCheck className="h-6 w-6 text-burgundy/55"/></div><Button className="mt-4 w-full" variant="secondary" onClick={()=>void analisar()} disabled={analisando}>{analisando?"Analisando…":"Executar / atualizar análise"}</Button></Panel>
  <Panel><SectionHeading title="Por que essa correspondência?" description="Cada ponto relevante fica visível para auditoria."/><div className="mt-4 space-y-2">{motivos.length?motivos.map((m:any,i:number)=><div key={i} className="flex gap-2 rounded-xl border border-rose/8 bg-white/50 p-3 text-[11px] dark:border-white/6 dark:bg-white/[0.02]"><span className={m.tipo==='positivo'?"text-success":"text-amber-600"}>{m.tipo==='positivo'?"✓":"⚠"}</span><span className="text-clay/65">{m.texto}{m.pontos?` · +${m.pontos}`:""}</span></div>):<div className="rounded-xl bg-blush/25 p-4 text-xs text-clay/50">Execute a análise para gerar os motivos.</div>}</div></Panel>
  <Panel><SectionHeading title="Cliente / carnê / boleto sugeridos"/><div className="mt-4 space-y-3">{clienteSelecionada&&<div className="rounded-xl border border-rose/8 p-3"><div className="flex items-center gap-2"><UserRound className="h-4 w-4 text-burgundy/50"/><p className="text-xs font-semibold text-burgundy">{clienteSelecionada.nome_completo}</p></div><p className="mt-1 text-[10px] text-clay/45">{clienteSelecionada.cpf?formatarCpf(clienteSelecionada.cpf):"CPF não informado"} · {clienteSelecionada.telefone??"Telefone não informado"}</p></div>}{carneSelecionado&&<div className="rounded-xl border border-rose/8 p-3"><p className="text-[9px] uppercase tracking-[0.14em] text-clay/40">Carnê</p><p className="mt-1 text-xs font-semibold text-burgundy">{carneSelecionado.identificador_externo}</p><p className="mt-1 text-[10px] text-clay/45">{carneSelecionado.instituicao_financeira} · {carneSelecionado.quantidade_parcelas??"—"} parcelas</p></div>}{selecionado&&<div className="rounded-xl border border-rose/8 p-3"><p className="text-[9px] uppercase tracking-[0.14em] text-clay/40">Boleto existente</p><p className="mt-1 text-xs font-semibold text-burgundy">Parcela {selecionado.numero_parcela}/{selecionado.total_parcelas}</p><p className="mt-1 text-[10px] text-clay/45">{formatarMoeda(Number(selecionado.valor))} · venc. {dataBR(selecionado.data_vencimento)} · status {selecionado.status}</p></div>}{!clienteSelecionada&&!carneSelecionado&&!selecionado&&<div className="rounded-xl bg-blush/25 p-4 text-xs text-clay/50">Nenhuma sugestão confiável ainda.</div>}</div></Panel>
  <Panel><SectionHeading title="Outras possibilidades" description="As alternativas são apresentadas para análise humana quando houver mais de uma correspondência."/><div className="mt-4 space-y-2">{candidatos.slice(1,4).map((c:any,i:number)=><div key={c.id} className="flex items-center justify-between rounded-xl border border-rose/8 p-3"><div><p className="text-xs font-semibold text-burgundy">Possibilidade {i+2}</p><p className="text-[10px] text-clay/45">{c.clientes?.nome_completo??"Cliente não identificada"} · parcela {c.numero_parcela??"—"}</p></div><StatusPill tone="neutral">{c.percentual}%</StatusPill></div>)}{candidatos.length<=1&&<p className="text-xs text-clay/45">Nenhuma outra correspondência relevante.</p>}</div></Panel></div>
 </div>
 <Panel><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-burgundy/55"/><div><p className="text-xs font-semibold text-burgundy">Proteção financeira</p><p className="mt-1 text-[10px] leading-5 text-clay/50">Confirmar esta vinculação apenas altera os relacionamentos da importação com cliente, carnê e boleto existente. Não dá baixa, não altera valor, vencimento, parcela ou status financeiro do boleto.</p></div><FileText className="ml-auto hidden h-4 w-4 text-burgundy/30 sm:block"/></div></Panel>
 </div>
}
