"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Check, Clock, CreditCard, FileCheck2, ShieldCheck, X } from "lucide-react";
import { Panel, SectionHeading, StatusPill } from "@/components/admin/ExecutiveUI";
import { Button } from "@/components/ui/Button";
import { formatarMoeda } from "@/lib/utils";
import { PRAZO_REVISAO_FINANCEIRA_DIAS_UTEIS } from "@/types/database";

interface Pendente { id: string; nome: string; cpf: string; valorContrato: number; quantidadeParcelas: number | null; porcentagemPagamento: number; dataAtingiuPercentual: string | null; }
interface Solicitacao { id: string; cliente_id: string; forma_custeio: "cartao" | "pix" | "cheques"; saldo_restante: number; taxa_cartao: number; total_com_taxa: number; status: "pendente" | "em_analise"; created_at: string; clientes?: { nome_completo: string; cpf: string; quantidade_parcelas: number | null }; }
function diasUteisDesde(iso: string | null) { if (!iso) return 0; const inicio = new Date(iso); const hoje = new Date(); const cursor = new Date(inicio); cursor.setHours(0,0,0,0); hoje.setHours(0,0,0,0); let dias = 0; while (cursor < hoje) { cursor.setDate(cursor.getDate()+1); const semana = cursor.getDay(); if (semana !== 0 && semana !== 6) dias += 1; } return dias; }

export function RevisaoFinanceiraCard() {
  const [pendentes, setPendentes] = useState<Pendente[]>([]); const [solicitacoes, setSolicitacoes] = useState<Solicitacao[]>([]); const [carregando, setCarregando] = useState(true); const [processando, setProcessando] = useState<string | null>(null);
  async function carregar() { try { const [resRevisao, resSolicitacoes] = await Promise.all([fetch("/api/admin/liberacoes-financeiras", { cache: "no-store" }), fetch("/api/admin/solicitacoes-liberacao-financeira", { cache: "no-store" })]); const revisao = await resRevisao.json(); const pedidos = await resSolicitacoes.json(); if (resRevisao.ok) setPendentes(revisao.pendentes ?? []); if (resSolicitacoes.ok) setSolicitacoes(pedidos.solicitacoes ?? []); } finally { setCarregando(false); } }
  useEffect(() => { carregar(); const intervalo = setInterval(carregar, 60_000); return () => clearInterval(intervalo); }, []);
  async function decidir(id: string, decisao: "aprovada" | "recusada") { if (decisao === "recusada") { const motivo = window.prompt("Descreva rapidamente a divergência encontrada no levantamento financeiro (opcional):"); if (motivo === null) return; await enviarDecisao(id, decisao, motivo); return; } await enviarDecisao(id, decisao); }
  async function enviarDecisao(id: string, decisao: "aprovada" | "recusada", observacao?: string) { setProcessando(id); try { const res = await fetch(`/api/admin/clientes/${id}/revisao-financeira`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decisao, observacao: observacao || undefined }) }); const data = await res.json(); if (!res.ok) { toast.error(data.erro ?? "Não foi possível registrar a decisão."); return; } toast.success(decisao === "aprovada" ? "Agenda liberada para a cliente." : "Revisão recusada. A cliente foi notificada de que há uma divergência."); setPendentes((atual) => atual.filter((p) => p.id !== id)); } catch { toast.error("Erro de conexão. Tente novamente."); } finally { setProcessando(null); } }
  async function atualizarSolicitacao(id: string, status: "em_analise" | "aprovada" | "recusada") { setProcessando(id); try { const res = await fetch("/api/admin/solicitacoes-liberacao-financeira", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); const data = await res.json(); if (!res.ok) { toast.error(data.erro ?? "Não foi possível atualizar a solicitação."); return; } toast.success(status === "aprovada" ? "Solicitação de custeio aprovada." : status === "recusada" ? "Solicitação recusada." : "Solicitação movida para análise."); setSolicitacoes((atual) => atual.filter((s) => s.id !== id)); } catch { toast.error("Erro de conexão. Tente novamente."); } finally { setProcessando(null); } }
  if (carregando) return null;
  return <div className="space-y-5">
    <Panel className="p-6"><SectionHeading title="Confirmação de agenda cirúrgica" description="Clientes que atingiram o percentual necessário e aguardam a confirmação do levantamento financeiro para liberar a agenda." aside={<StatusPill tone={pendentes.length > 0 ? "rose" : "neutral"}>{pendentes.length} pendente(s)</StatusPill>} />
      {pendentes.length === 0 ? <div className="flex flex-col items-center gap-2 rounded-[28px] border border-dashed border-rose/20 bg-blush/30 px-6 py-10 text-center"><ShieldCheck className="h-6 w-6 text-clay/30" /><p className="text-sm text-clay/55">Nenhuma cliente aguardando confirmação de agenda cirúrgica no momento.</p></div> : <div className="space-y-3">{pendentes.map((c) => { const dias = diasUteisDesde(c.dataAtingiuPercentual); const atrasado = dias >= PRAZO_REVISAO_FINANCEIRA_DIAS_UTEIS; return <div key={c.id} className="grid gap-4 rounded-[26px] border border-rose/10 bg-blush/30 p-4 lg:grid-cols-[1.3fr_0.8fr_0.9fr_auto]"><div className="min-w-0"><p className="truncate text-base text-burgundy">{c.nome}</p><p className="text-xs text-clay/45">{formatarMoeda(c.valorContrato)} · {c.quantidadeParcelas ?? "—"}x</p></div><div><p className="text-xs uppercase tracking-[0.22em] text-clay/40">Pagamento</p><p className="mt-1 text-sm font-semibold text-burgundy">{c.porcentagemPagamento}%</p></div><div><p className="text-xs uppercase tracking-[0.22em] text-clay/40">Prazo (5 dias úteis)</p><p className={`mt-1 flex items-center gap-1.5 text-sm ${atrasado ? "text-alert" : "text-burgundy"}`}><Clock className="h-3.5 w-3.5" />{atrasado ? "Prazo atingido" : `${dias}/${PRAZO_REVISAO_FINANCEIRA_DIAS_UTEIS} dias úteis`}</p></div><div className="flex items-center gap-2"><Button size="sm" variant="secondary" loading={processando === c.id} onClick={() => decidir(c.id, "recusada")} className="!text-alert"><X className="h-3.5 w-3.5" /> Recusar</Button><Button size="sm" loading={processando === c.id} onClick={() => decidir(c.id, "aprovada")}><Check className="h-3.5 w-3.5" /> Confirmar</Button></div></div>; })}</div>}
    </Panel>
    <Panel className="p-6"><SectionHeading title="Solicitações de liberação financeira" description="Clientes com agenda liberada que já informaram como pretendem custear o saldo restante do contrato." aside={<StatusPill tone={solicitacoes.length > 0 ? "rose" : "neutral"}>{solicitacoes.length} nova(s)</StatusPill>} />
      {solicitacoes.length === 0 ? <div className="flex items-center justify-center rounded-[28px] border border-dashed border-rose/20 bg-blush/30 px-6 py-8 text-center"><p className="text-sm text-clay/55">Nenhuma solicitação de custeio aguardando análise.</p></div> : <div className="space-y-3">{solicitacoes.map((s) => { const forma = s.forma_custeio === "cartao" ? "Cartão de crédito" : s.forma_custeio === "pix" ? "PIX" : "Cheques"; const Icone = s.forma_custeio === "cartao" ? CreditCard : FileCheck2; return <div key={s.id} className="rounded-[26px] border border-rose/10 bg-blush/30 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-burgundy/10"><Icone className="h-4 w-4 text-burgundy" /></span><div><p className="text-base text-burgundy">{s.clientes?.nome_completo ?? "Cliente"}</p><p className="text-xs text-clay/45">{forma} · recebido em {new Date(s.created_at).toLocaleString("pt-BR")}</p></div></div><div className="text-right"><p className="text-xs uppercase tracking-[0.18em] text-clay/40">Saldo</p><p className="text-lg font-semibold text-burgundy">{formatarMoeda(Number(s.saldo_restante))}</p>{s.forma_custeio === "cartao" && <p className="text-[0.68rem] text-clay/50">com taxa: {formatarMoeda(Number(s.total_com_taxa))}</p>}</div></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="secondary" loading={processando === s.id} onClick={() => atualizarSolicitacao(s.id, "em_analise")}><Clock className="h-3.5 w-3.5" /> Em análise</Button><Button size="sm" loading={processando === s.id} onClick={() => atualizarSolicitacao(s.id, "recusada")} className="!text-alert"><X className="h-3.5 w-3.5" /> Recusar</Button><Button size="sm" loading={processando === s.id} onClick={() => atualizarSolicitacao(s.id, "aprovada")}><Check className="h-3.5 w-3.5" /> Aprovar</Button></div></div>; })}</div>}
    </Panel>
  </div>;
}
